name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: Image Version
        required: true
    
jobs:
  test_variables:
    name: Testando variaveis
    runs-on: ubuntu-latest
    
    steps:
    - name: Exibindo variáveis 
      run: |
        echo "{{ github.event }}"
        echo "{{ github.repository.name }}"
        echo "{{ inputs.image_version }}"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag {{ }}:$(date +%s)
