name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: Image Version
        required: true
    
jobs:
  test_variables:
    name: Testando variaveis
    runs-on: ubuntu-latest
    
    steps:
    - name: Exibindo variáveis 
      run: |
        echo "${{ github.event }}"
        echo "${{ github.event.repository.name }}"
        echo "${{ inputs.image_version }}"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: robertsilvatech/${{ github.event.repository.name }}:${{ inputs.image_version }}
