name: Docker Image CI
run-name: Build image version ${{ inputs.image_version }} from master

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: Image Version
        required: true
    
jobs:
  docker_build_push:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: robertsilvatech/${{ github.event.repository.name }}:${{ inputs.image_version }}
